name: hivebox-ci

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hivebox-build-and-test:
    runs-on: ubuntu-latest
    outputs:
      built: ${{ steps.build.outputs.built }}
      image_version: ${{ steps.build.outputs.image_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      # Linting 
      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Lint Python source
        run: docker run --rm -v $(pwd):/app cytopia/pylint pylint /app/src/*.py --fail-under=7.0

        # Build and beyond only happens in case of the latest commit having a tag
      - name: building the docker image for hivebox
        id: build
        if: startsWith(github.ref, 'refs/tags/')
        run: ./build.sh

        
      # 3- Testing (unit and integration)
      # Only runs if the build runs successfully
      - name: Unit Testing
        if: steps.build.outputs.built == 'true'
        run: docker run --rm --entrypoint uv hivebox:latest run pytest tests/

        # 4. pushing the image to registry + save and upload the version to use in CD
      - name: Log in to GHCR
        if: steps.build.outputs.built == 'true'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry after renaming it according to the standards.
        if: steps.build.outputs.built == 'true'
        run: |
          # change tag to suit the 
          docker tag hivebox:${{ steps.build.outputs.image_version }} ghcr.io/${{ github.repository_owner }}/hivebox:${{ steps.build.outputs.image_version }}
          docker push ghcr.io/${{ github.repository_owner }}/hivebox:${{ steps.build.outputs.image_version }}

      - name: Save image version
        if: steps.build.outputs.built == 'true'
        run: echo "${{ steps.build.outputs.image_version }}" > image_version.txt

      - name: Upload version artifact
        if: steps.build.outputs.built == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1 
        with:
          name: image-version
          path: image_version.txt
          
  # Setting up OSSF scoreboard
  ossf_scorecard:
    needs: hivebox-build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@29181f28d55fcc032f21a33f8ad0847965867c55 #v3.1.5
        with:
          sarif_file: results.sarif

  semgrep_sast_scanner:
    needs: hivebox-build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to post results back to GitHub Security
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Semgrep Python Security Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/python # Tells Semgrep to look specifically for Python vulnerabilities
          generateSarif: "1"
      - name: Upload Semgrep results to GitHub Security
        uses: github/codeql-action/upload-sarif@84498526a009a99c875e83ef4821a8ba52de7c22 # v2.25.5
        if: always()
        with:
          sarif_file: 'semgrep.sarif'

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./k8s_manifests
          framework: kubernetes
          output_format: sarif
          output_file_path: checkov.sarif
        continue-on-error: true

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@84498526a009a99c875e83ef4821a8ba52de7c22 # v2.25.5
        if: always()
        with:
          sarif_file: 'checkov.sarif'